//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IronProlog/Grammar/Prolog.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace IronProlog.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PrologParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IPrologListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.knowledge_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKnowledge_base([NotNull] PrologParser.Knowledge_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.knowledge_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKnowledge_base([NotNull] PrologParser.Knowledge_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClause([NotNull] PrologParser.ClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClause([NotNull] PrologParser.ClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFact([NotNull] PrologParser.FactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFact([NotNull] PrologParser.FactContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule([NotNull] PrologParser.RuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule([NotNull] PrologParser.RuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate([NotNull] PrologParser.PredicateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.predicate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate([NotNull] PrologParser.PredicateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctor([NotNull] PrologParser.FunctorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctor([NotNull] PrologParser.FunctorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>predicate_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPredicate_term([NotNull] PrologParser.Predicate_termContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>predicate_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPredicate_term([NotNull] PrologParser.Predicate_termContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atom_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom_term([NotNull] PrologParser.Atom_termContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atom_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom_term([NotNull] PrologParser.Atom_termContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variable_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_term([NotNull] PrologParser.Variable_termContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variable_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_term([NotNull] PrologParser.Variable_termContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>number_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber_term([NotNull] PrologParser.Number_termContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>number_term</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber_term([NotNull] PrologParser.Number_termContext context);
}
} // namespace IronProlog.Parser
