//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar/Prolog.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace IronProlog.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public partial class PrologLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, ATOM=3, VARIABLE=4, NUMBER=5, COMMA=6, STOP=7, WHITESPACE=8;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "ATOM", "VARIABLE", "NUMBER", "COMMA", "STOP", "WHITESPACE"
	};


	public PrologLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PrologLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'('", "')'", null, null, null, "','", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, "ATOM", "VARIABLE", "NUMBER", "COMMA", "STOP", "WHITESPACE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Prolog.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PrologLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,8,65,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,1,0,1,0,1,1,1,1,1,2,1,2,5,2,24,8,2,10,2,12,2,27,9,2,1,2,1,2,4,
		2,31,8,2,11,2,12,2,32,1,2,3,2,36,8,2,1,3,1,3,5,3,40,8,3,10,3,12,3,43,9,
		3,1,4,4,4,46,8,4,11,4,12,4,47,1,4,1,4,4,4,52,8,4,11,4,12,4,53,3,4,56,8,
		4,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,1,32,0,8,1,1,3,2,5,3,7,4,9,5,11,6,13,
		7,15,8,1,0,5,1,0,97,122,3,0,65,90,95,95,97,122,1,0,65,90,1,0,48,57,3,0,
		9,10,13,13,32,32,71,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,
		9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,1,17,1,0,0,0,3,19,1,0,
		0,0,5,35,1,0,0,0,7,37,1,0,0,0,9,45,1,0,0,0,11,57,1,0,0,0,13,59,1,0,0,0,
		15,61,1,0,0,0,17,18,5,40,0,0,18,2,1,0,0,0,19,20,5,41,0,0,20,4,1,0,0,0,
		21,25,7,0,0,0,22,24,7,1,0,0,23,22,1,0,0,0,24,27,1,0,0,0,25,23,1,0,0,0,
		25,26,1,0,0,0,26,36,1,0,0,0,27,25,1,0,0,0,28,30,5,39,0,0,29,31,9,0,0,0,
		30,29,1,0,0,0,31,32,1,0,0,0,32,33,1,0,0,0,32,30,1,0,0,0,33,34,1,0,0,0,
		34,36,5,39,0,0,35,21,1,0,0,0,35,28,1,0,0,0,36,6,1,0,0,0,37,41,7,2,0,0,
		38,40,7,1,0,0,39,38,1,0,0,0,40,43,1,0,0,0,41,39,1,0,0,0,41,42,1,0,0,0,
		42,8,1,0,0,0,43,41,1,0,0,0,44,46,7,3,0,0,45,44,1,0,0,0,46,47,1,0,0,0,47,
		45,1,0,0,0,47,48,1,0,0,0,48,55,1,0,0,0,49,51,5,46,0,0,50,52,7,3,0,0,51,
		50,1,0,0,0,52,53,1,0,0,0,53,51,1,0,0,0,53,54,1,0,0,0,54,56,1,0,0,0,55,
		49,1,0,0,0,55,56,1,0,0,0,56,10,1,0,0,0,57,58,5,44,0,0,58,12,1,0,0,0,59,
		60,5,46,0,0,60,14,1,0,0,0,61,62,7,4,0,0,62,63,1,0,0,0,63,64,6,7,0,0,64,
		16,1,0,0,0,8,0,25,32,35,41,47,53,55,1,0,1,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace IronProlog.Parser
