//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IronProlog/Grammar/Prolog.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace IronProlog.Parser {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PrologParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IPrologListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.knowledge_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKnowledge_base([NotNull] PrologParser.Knowledge_baseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.knowledge_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKnowledge_base([NotNull] PrologParser.Knowledge_baseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClause([NotNull] PrologParser.ClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClause([NotNull] PrologParser.ClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFact([NotNull] PrologParser.FactContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.fact"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFact([NotNull] PrologParser.FactContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule([NotNull] PrologParser.RuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule([NotNull] PrologParser.RuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplex([NotNull] PrologParser.ComplexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.complex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplex([NotNull] PrologParser.ComplexContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryBody</c>
	/// labeled alternative in <see cref="PrologParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryBody([NotNull] PrologParser.UnaryBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryBody</c>
	/// labeled alternative in <see cref="PrologParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryBody([NotNull] PrologParser.UnaryBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>connectiveBody</c>
	/// labeled alternative in <see cref="PrologParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnectiveBody([NotNull] PrologParser.ConnectiveBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>connectiveBody</c>
	/// labeled alternative in <see cref="PrologParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnectiveBody([NotNull] PrologParser.ConnectiveBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctor([NotNull] PrologParser.FunctorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.functor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctor([NotNull] PrologParser.FunctorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] PrologParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] PrologParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.deconstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeconstruct([NotNull] PrologParser.DeconstructContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.deconstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeconstruct([NotNull] PrologParser.DeconstructContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PrologParser.head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHead([NotNull] PrologParser.HeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PrologParser.head"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHead([NotNull] PrologParser.HeadContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>termItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTermItem([NotNull] PrologParser.TermItemContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>termItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTermItem([NotNull] PrologParser.TermItemContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variableItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableItem([NotNull] PrologParser.VariableItemContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variableItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableItem([NotNull] PrologParser.VariableItemContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ignoreItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIgnoreItem([NotNull] PrologParser.IgnoreItemContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ignoreItem</c>
	/// labeled alternative in <see cref="PrologParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIgnoreItem([NotNull] PrologParser.IgnoreItemContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variableTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableTail([NotNull] PrologParser.VariableTailContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variableTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableTail([NotNull] PrologParser.VariableTailContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>emptyTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyTail([NotNull] PrologParser.EmptyTailContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>emptyTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyTail([NotNull] PrologParser.EmptyTailContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ignoreTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIgnoreTail([NotNull] PrologParser.IgnoreTailContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ignoreTail</c>
	/// labeled alternative in <see cref="PrologParser.tail"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIgnoreTail([NotNull] PrologParser.IgnoreTailContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>complexTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexTerm([NotNull] PrologParser.ComplexTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>complexTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexTerm([NotNull] PrologParser.ComplexTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>listTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListTerm([NotNull] PrologParser.ListTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>listTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListTerm([NotNull] PrologParser.ListTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>deconstructTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeconstructTerm([NotNull] PrologParser.DeconstructTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>deconstructTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeconstructTerm([NotNull] PrologParser.DeconstructTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>atomTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtomTerm([NotNull] PrologParser.AtomTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>atomTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtomTerm([NotNull] PrologParser.AtomTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variableTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableTerm([NotNull] PrologParser.VariableTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variableTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableTerm([NotNull] PrologParser.VariableTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>numberTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberTerm([NotNull] PrologParser.NumberTermContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>numberTerm</c>
	/// labeled alternative in <see cref="PrologParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberTerm([NotNull] PrologParser.NumberTermContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="PrologParser.connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd([NotNull] PrologParser.AndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>and</c>
	/// labeled alternative in <see cref="PrologParser.connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd([NotNull] PrologParser.AndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="PrologParser.connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr([NotNull] PrologParser.OrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>or</c>
	/// labeled alternative in <see cref="PrologParser.connective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr([NotNull] PrologParser.OrContext context);
}
} // namespace IronProlog.Parser
